# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/butler.site"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Nuget
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for .net-sdk
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"

  # Enable version updates for Nuget
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
